/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jorge
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        lblCaballo1 = new javax.swing.JLabel();
        lblCaballo2 = new javax.swing.JLabel();
        lblCaballo3 = new javax.swing.JLabel();
        lblCaballo4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblBandera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        lblCaballo5 = new javax.swing.JLabel();
        lblCaballo6 = new javax.swing.JLabel();
        lblCaballo7 = new javax.swing.JLabel();
        lblCaballo8 = new javax.swing.JLabel();
        lblCaballo9 = new javax.swing.JLabel();
        lblCaballo10 = new javax.swing.JLabel();
        lblLinea1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linea.png"))); // NOI18N

        lblCaballo1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandera.png"))); // NOI18N

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblCaballo5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo6.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo7.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo8.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo9.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblCaballo10.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCaballo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N

        lblLinea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linea.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaballo10)
                    .addComponent(lblCaballo1)
                    .addComponent(lblCaballo3)
                    .addComponent(lblCaballo2)
                    .addComponent(lblCaballo4)
                    .addComponent(lblCaballo5)
                    .addComponent(lblCaballo7)
                    .addComponent(lblCaballo9)
                    .addComponent(lblCaballo6)
                    .addComponent(lblCaballo8))
                .addGap(562, 562, 562)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLinea)
                    .addComponent(lblLinea1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBandera)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(lblCaballo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblCaballo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCaballo3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCaballo4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblCaballo5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCaballo6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCaballo7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaballo8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblCaballo9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblCaballo10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblLinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(379, 379, 379))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addComponent(lblBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        carrera.registrarCaballos();
        lblCaballo1.setText(carrera.losCaballos[0].getNombre());
        lblCaballo2.setText(carrera.losCaballos[1].getNombre());
        lblCaballo3.setText(carrera.losCaballos[2].getNombre());
        lblCaballo4.setText(carrera.losCaballos[3].getNombre());
        lblCaballo5.setText(carrera.losCaballos[4].getNombre());
        lblCaballo6.setText(carrera.losCaballos[5].getNombre());
        lblCaballo7.setText(carrera.losCaballos[6].getNombre());
        lblCaballo8.setText(carrera.losCaballos[7].getNombre());
        lblCaballo9.setText(carrera.losCaballos[8].getNombre());
        lblCaballo10.setText(carrera.losCaballos[9].getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carrera.reiniciar();
        lblCaballo1.setLocation(carrera.losCaballos[0].getCoorX(),carrera.losCaballos[0].getCoorY());
        lblCaballo2.setLocation(carrera.losCaballos[1].getCoorX(),carrera.losCaballos[1].getCoorY());
        lblCaballo3.setLocation(carrera.losCaballos[2].getCoorX(),carrera.losCaballos[2].getCoorY());
        lblCaballo4.setLocation(carrera.losCaballos[3].getCoorX(),carrera.losCaballos[3].getCoorY());
        lblCaballo5.setLocation(carrera.losCaballos[4].getCoorX(),carrera.losCaballos[4].getCoorY());
        lblCaballo6.setLocation(carrera.losCaballos[5].getCoorX(),carrera.losCaballos[5].getCoorY());
        lblCaballo7.setLocation(carrera.losCaballos[6].getCoorX(),carrera.losCaballos[6].getCoorY());
        lblCaballo8.setLocation(carrera.losCaballos[7].getCoorX(),carrera.losCaballos[7].getCoorY());
        lblCaballo9.setLocation(carrera.losCaballos[8].getCoorX(),carrera.losCaballos[8].getCoorY());
        lblCaballo10.setLocation(carrera.losCaballos[9].getCoorX(),carrera.losCaballos[9].getCoorY());
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        frmInicio.txtR.setText("->");
        carrera.iniciar();
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblBandera;
    public static javax.swing.JLabel lblCaballo1;
    public static javax.swing.JLabel lblCaballo10;
    public static javax.swing.JLabel lblCaballo2;
    public static javax.swing.JLabel lblCaballo3;
    public static javax.swing.JLabel lblCaballo4;
    public static javax.swing.JLabel lblCaballo5;
    public static javax.swing.JLabel lblCaballo6;
    public static javax.swing.JLabel lblCaballo7;
    public static javax.swing.JLabel lblCaballo8;
    public static javax.swing.JLabel lblCaballo9;
    public static javax.swing.JLabel lblLinea;
    public static javax.swing.JLabel lblLinea1;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
